# Generated by Django 4.1.2 on 2022-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, max_length=15),
        ),
    ]
