# Generated by Django 4.1.2 on 2022-10-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0006_alter_product_price_alter_product_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='', max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(max_length=1024, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=1024, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_value',
            field=models.TextField(max_length=512, verbose_name='Пищевая ценность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='Масса'),
        ),
    ]
