# Generated by Django 4.1.2 on 2022-10-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0007_alter_product_options_remove_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(default=None, verbose_name='Цена'),
        ),
    ]
