# Generated by Django 4.1.2 on 2022-10-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0008_product_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(verbose_name='Цена'),
        ),
    ]
