# Generated by Django 4.1.2 on 2022-10-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0009_alter_product_price_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(default=None, max_length=100, verbose_name='Наименование'),
        ),
    ]
