# Generated by Django 4.1.2 on 2022-10-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_store', '0010_alter_product_price_with_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutritional_value',
            field=models.TextField(blank=True, default=None, max_length=512, null=True, verbose_name='Пищевая ценность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_with_discount',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Масса'),
        ),
    ]
